package com.splanes.apps.petchat.presentation.common.theme.colors

import androidx.compose.ui.graphics.Color

internal val primaryDark = Color(0xFF80D4DB)
internal val onPrimaryDark = Color(0xFF00363A)
internal val primaryContainerDark = Color(0xFF004F54)
internal val onPrimaryContainerDark = Color(0xFF9DF0F7)
internal val secondaryDark = Color(0xFFB1CBCE)
internal val onSecondaryDark = Color(0xFF1B3436)
internal val secondaryContainerDark = Color(0xFF324B4D)
internal val onSecondaryContainerDark = Color(0xFFCCE8EA)
internal val tertiaryDark = Color(0xFFB7C7EA)
internal val onTertiaryDark = Color(0xFF20304C)
internal val tertiaryContainerDark = Color(0xFF374764)
internal val onTertiaryContainerDark = Color(0xFFD7E3FF)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF0E1415)
internal val onBackgroundDark = Color(0xFFDDE4E4)
internal val surfaceDark = Color(0xFF0E1415)
internal val onSurfaceDark = Color(0xFFDDE4E4)
internal val surfaceVariantDark = Color(0xFF3F4849)
internal val onSurfaceVariantDark = Color(0xFFBEC8C9)
internal val outlineDark = Color(0xFF899393)
internal val outlineVariantDark = Color(0xFF3F4849)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFDDE4E4)
internal val inverseOnSurfaceDark = Color(0xFF2B3232)
internal val inversePrimaryDark = Color(0xFF00696F)
internal val surfaceDimDark = Color(0xFF0E1415)
internal val surfaceBrightDark = Color(0xFF343A3B)
internal val surfaceContainerLowestDark = Color(0xFF090F10)
internal val surfaceContainerLowDark = Color(0xFF161D1D)
internal val surfaceContainerDark = Color(0xFF1A2121)
internal val surfaceContainerHighDark = Color(0xFF252B2C)
internal val surfaceContainerHighestDark = Color(0xFF303636)
internal val successDark = Color(0xFF93D5A9)
internal val onSuccessDark = Color(0xFF00391F)
internal val successContainerDark = Color(0xFF0B5130)
internal val onSuccessContainerDark = Color(0xFFAFF2C4)
internal val warningDark = Color(0xFFF8BB71)
internal val onWarningDark = Color(0xFF472A00)
internal val warningContainerDark = Color(0xFF663E00)
internal val onWarningContainerDark = Color(0xFFFFDDB9)

internal val DarkColorScheme = AppColorScheme(
  primary = primaryDark,
  onPrimary = onPrimaryDark,
  primaryContainer = primaryContainerDark,
  onPrimaryContainer = onPrimaryContainerDark,
  inversePrimary = inversePrimaryDark,
  secondary = secondaryDark,
  onSecondary = onSecondaryDark,
  secondaryContainer = secondaryContainerDark,
  onSecondaryContainer = onSecondaryContainerDark,
  tertiary = tertiaryDark,
  onTertiary = onTertiaryDark,
  tertiaryContainer = tertiaryContainerDark,
  onTertiaryContainer = onTertiaryContainerDark,
  background = backgroundDark,
  onBackground = onBackgroundDark,
  surface = surfaceDark,
  onSurface = onSurfaceDark,
  surfaceVariant = surfaceVariantDark,
  onSurfaceVariant = onSurfaceVariantDark,
  surfaceTint = primaryDark,
  inverseSurface = inverseSurfaceDark,
  inverseOnSurface = inverseOnSurfaceDark,
  error = errorDark,
  onError = onErrorDark,
  errorContainer = errorContainerDark,
  onErrorContainer = onErrorContainerDark,
  outline = outlineDark,
  outlineVariant = outlineVariantDark,
  scrim = scrimDark,
  surfaceBright = surfaceBrightDark,
  surfaceDim = surfaceDimDark,
  surfaceContainer = surfaceContainerDark,
  surfaceContainerHigh = surfaceContainerHighDark,
  surfaceContainerHighest = surfaceContainerHighestDark,
  surfaceContainerLow = surfaceContainerLowDark,
  surfaceContainerLowest = surfaceContainerLowestDark,
  success = successDark,
  onSuccess = onSuccessDark,
  successContainer = successContainerDark,
  onSuccessContainer = onSuccessContainerDark,
  warning = warningDark,
  onWarning = onWarningDark,
  warningContainer = warningContainerDark,
  onWarningContainer = onWarningContainerDark,
)