package com.splanes.apps.petchat.presentation.common.theme.colors

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF00696F)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFF9DF0F7)
internal val onPrimaryContainerLight = Color(0xFF004F54)
internal val secondaryLight = Color(0xFF4A6365)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFCCE8EA)
internal val onSecondaryContainerLight = Color(0xFF324B4D)
internal val tertiaryLight = Color(0xFF4F5F7D)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFD7E3FF)
internal val onTertiaryContainerLight = Color(0xFF374764)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF4FAFB)
internal val onBackgroundLight = Color(0xFF161D1D)
internal val surfaceLight = Color(0xFFF4FAFB)
internal val onSurfaceLight = Color(0xFF161D1D)
internal val surfaceVariantLight = Color(0xFFDAE4E5)
internal val onSurfaceVariantLight = Color(0xFF3F4849)
internal val outlineLight = Color(0xFF6F797A)
internal val outlineVariantLight = Color(0xFFBEC8C9)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2B3232)
internal val inverseOnSurfaceLight = Color(0xFFECF2F2)
internal val inversePrimaryLight = Color(0xFF80D4DB)
internal val surfaceDimLight = Color(0xFFD5DBDB)
internal val surfaceBrightLight = Color(0xFFF4FAFB)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFEFF5F5)
internal val surfaceContainerLight = Color(0xFFE9EFEF)
internal val surfaceContainerHighLight = Color(0xFFE3E9E9)
internal val surfaceContainerHighestLight = Color(0xFFDDE4E4)
internal val successLight = Color(0xFF2A6A47)
internal val onSuccessLight = Color(0xFFFFFFFF)
internal val successContainerLight = Color(0xFFAFF2C4)
internal val onSuccessContainerLight = Color(0xFF0B5130)
internal val warningLight = Color(0xFF825513)
internal val onWarningLight = Color(0xFFFFFFFF)
internal val warningContainerLight = Color(0xFFFFDDB9)
internal val onWarningContainerLight = Color(0xFF663E00)

internal val LightColorScheme = AppColorScheme(
  primary = primaryLight,
  onPrimary = onPrimaryLight,
  primaryContainer = primaryContainerLight,
  onPrimaryContainer = onPrimaryContainerLight,
  inversePrimary = inversePrimaryLight,
  secondary = secondaryLight,
  onSecondary = onSecondaryLight,
  secondaryContainer = secondaryContainerLight,
  onSecondaryContainer = onSecondaryContainerLight,
  tertiary = tertiaryLight,
  onTertiary = onTertiaryLight,
  tertiaryContainer = tertiaryContainerLight,
  onTertiaryContainer = onTertiaryContainerLight,
  background = backgroundLight,
  onBackground = onBackgroundLight,
  surface = surfaceLight,
  onSurface = onSurfaceLight,
  surfaceVariant = surfaceVariantLight,
  onSurfaceVariant = onSurfaceVariantLight,
  surfaceTint = primaryLight,
  inverseSurface = inverseSurfaceLight,
  inverseOnSurface = inverseOnSurfaceLight,
  error = errorLight,
  onError = onErrorLight,
  errorContainer = errorContainerLight,
  onErrorContainer = onErrorContainerLight,
  outline = outlineLight,
  outlineVariant = outlineVariantLight,
  scrim = scrimLight,
  surfaceBright = surfaceBrightLight,
  surfaceDim = surfaceDimLight,
  surfaceContainer = surfaceContainerLight,
  surfaceContainerHigh = surfaceContainerHighLight,
  surfaceContainerHighest = surfaceContainerHighestLight,
  surfaceContainerLow = surfaceContainerLowLight,
  surfaceContainerLowest = surfaceContainerLowestLight,
  success = successLight,
  onSuccess = onSuccessLight,
  successContainer = successContainerLight,
  onSuccessContainer = onSuccessContainerLight,
  warning = warningLight,
  onWarning = onWarningLight,
  warningContainer = warningContainerLight,
  onWarningContainer = onWarningContainerLight,
)